<h1>Welcome to your <?= $framework; ?> Skeleton Application</h1>
<p>
    <b>Configured with:</b>
    <ul>
        <li>Zend Config</li>
        <li>Zend Service Manager</li>
        <li>Zend Di</li>
        <li>Zend Db Adapter</li>
    </ul>
</p>
<?php if (isset($db)) : ?>
    <h2>Tables in the <?= $db ?> Database</h2>
    <?php if (count($tables) > 0) : ?>
        <ul>
            <?php foreach ($tables as $table) : ?>
                <li><?= $table['Tables_in_' . $db] ?></li>
            <?php endforeach; ?>
        </ul>
    <?php else : ?>
        No Tables Found
    <?php endif; ?>
<?php else : ?>
    <h2>No Database was specified on init of skeleton</h2>
<?php endif; ?>
