# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: channelgrabber/php71

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - echo '127.0.0.1 mysql' >> /etc/hosts
          - php bin/nullify_composer_lock_sha.php
          - composer install --no-progress --no-suggest --prefer-dist  --ignore-platform-reqs
          - vendor/bin/phpunit --log-junit ./test-reports/junit.xml
          - vendor/bin/phpunit --group=integration --log-junit ./test-reports/junit.integration.xml
        services:
          - mysql
definitions:
  services:
    mysql:
      image: percona:5.6
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: cg_app
        MYSQL_USER: phpunit
        MYSQL_PASSWORD: phpunit