# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: channelgrabber/php71

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - php bin/nullify_composer_lock_sha.php
          - composer install --no-progress --no-suggest --prefer-dist  --ignore-platform-reqs
          - vendor/bin/phpunit