# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: channelgrabber/php71

pipelines:
  default:
    - step:
        name: Composer Install
        caches:
          - composer
        script:
          - php bin/nullify_composer_lock_sha.php
          - composer install --no-progress --no-suggest --prefer-dist  --ignore-platform-reqs
        artifacts:
          - vendor/**
    - parallel:
        - step:
            name: Unit Tests
            script:
              - vendor/bin/phpunit --log-junit ./test-reports/junit.xml
        - step:
            name: Integration Tests
            script:
              - echo '127.0.0.1 mysql' >> /etc/hosts
              - vendor/bin/phpunit --group=integration --log-junit ./test-reports/junit.integration.xml
            services:
              - mysql
        - step:
            name: Static Analysis
            script:
              - mkdir -p ./test-reports
              - vendor/bin/phpstan analyse --error-format junit > ./test-reports/junit.analysis.xml

definitions:
  services:
    mysql:
      image: percona:5.7
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: cg_app
        MYSQL_USER: phpunit
        MYSQL_PASSWORD: phpunit