<?php
/*
 * This file is generated but should still be committed
 */
return array(
    'channelgrabber_cache_CG_Cache',
    'channelgrabber_constants_CG',
    'channelgrabber_etag_CG_ETag',
    'channelgrabber_http_CG_Http',
    'channelgrabber_order_CG_Order',
//    'channelgrabber_phinx_src_Phinx',
    'channelgrabber_phpunit_CG_PhpUnit',
    'channelgrabber_predis_CG_Predis',
    'channelgrabber_slim_CG_Slim',
    'channelgrabber_stdlib_CG_Stdlib',
//    'channelgrabber_userpreference_CG_UserPreference',
    'channelgrabber_validation_CG_Validation',
    'channelgrabber_vnderror_CG_VndError',
    'cilex_cilex_src_Cilex',
//    'cilex_console-service-provider_src_Cilex',
//    'codeception_codeception_src_Codeception',
    'fabpot_goutte_Goutte',
    'guzzle_guzzle_src_Guzzle',
    'nocarrier_hal_src_Nocarrier',
    'phpspec_php-diff_lib_Diff',
//    'phpspec_phpspec_src_PhpSpec',
    'phpspec_prophecy_src_Prophecy',
//    'pimple_pimple_lib_Pimple',
    'predis_predis_lib_Predis',
    'psr_log_Psr_Log',
    'rhumsaa_vnderror_src_Rhumsaa_VndError',
    'predis_predis_lib_Predis',
    'slim_slim_Slim',
//    'symfony_class-loader_Symfony_Component_ClassLoader',
//    'symfony_config_Symfony_Component_Config',
//    'symfony_console_Symfony_Component_Console',
//    'symfony_event-dispatcher_Symfony_Component_EventDispatcher',
//    'symfony_filesystem_Symfony_Component_Filesystem',
//    'symfony_yaml_Symfony_Component_Yaml',
//    'zendframework_zend-code_Zend_Code',
    'zendframework_zend-config_Zend_Config',
    'zendframework_zend-db_Zend_Db',
    'zendframework_zend-di_Zend_Di',
    'zendframework_zend-eventmanager_Zend',
    'zendframework_zend-filter_Zend_Filter',
    'zendframework_zend-inputfilter_Zend',
    'zendframework_zend-servicemanager_Zend',
    'zendframework_zend-stdlib_Zend_Stdlib',
//    'zendframework_zend-validator_Zend_Validator',
);