<?php
/*
 * This file is generated but should still be committed
 */
return array(
    'alexandresalome_php-selenium_src_Selenium',
    'behat_mink-browserkit-driver_src_Behat_Mink_Driver',
    'behat_mink-goutte-driver_src_Behat_Mink_Driver',
    'behat_mink-selenium-driver_src_Behat_Mink_Driver',
    'behat_mink-selenium2-driver_src_Behat_Mink_Driver',
    'behat_mink-zombie-driver_src_Behat_Mink_Driver',
    'behat_mink_src_Behat_Mink',
    'channelgrabber_cache_CG_Cache',
//    'channelgrabber_codeception_CG_Codeception',
    'channelgrabber_http_CG_Http',
    'channelgrabber_predis_CG_Predis',
    'channelgrabber_stdlib_CG_Stdlib',
    'channelgrabber_zf2-stdlib_CG_Zend_Stdlib',
    'codeception_codeception_src_Codeception',
    'fabpot_goutte_Goutte',
    'guzzle_guzzle_src_Guzzle',
    'instaclick_php-webdriver_lib_WebDriver',
    'monolog_monolog_src_Monolog',
    'nocarrier_hal_src_Nocarrier',
    'phpspec_php-diff_lib_Diff',
    'phpspec_phpspec_src_PhpSpec',
    'phpspec_prophecy_src_Prophecy',
    'predis_predis_lib_Predis',
    'psr_log_Psr_Log',
    'symfony_browser-kit_Symfony_Component_BrowserKit',
    'symfony_console_Symfony_Component_Console',
    'symfony_css-selector_Symfony_Component_CssSelector',
    'symfony_dom-crawler_Symfony_Component_DomCrawler',
    'symfony_event-dispatcher_Symfony_Component_EventDispatcher',
    'symfony_finder_Symfony_Component_Finder',
    'symfony_process_Symfony_Component_Process',
    'symfony_yaml_Symfony_Component_Yaml',
    'videlalvaro_php-amqplib_PhpAmqpLib',
//    'zendframework_zend-code_Zend_Code',
    'zendframework_zend-config_Zend_Config',
    'zendframework_zend-db_Zend_Db',
    'zendframework_zend-di_Zend_Di',
    'zendframework_zend-escaper_Zend_Escaper',
    'zendframework_zend-eventmanager_Zend',
    'zendframework_zend-http_Zend_Http',
    'zendframework_zend-loader_Zend_Loader',
    'zendframework_zend-servicemanager_Zend',
    'zendframework_zend-stdlib_Zend_Stdlib',
    'zendframework_zend-uri_Zend_Uri',
//    'zendframework_zend-validator_Zend_Validator',
//    'zendframework_zend-view_Zend_View',
);