<?php
/*
 * This file is generated but should still be committed
 */
return array(
    'behat_mink-browserkit-driver_src_Behat_Mink_Driver',
    'behat_mink-goutte-driver_src_Behat_Mink_Driver',
    'behat_mink-selenium2-driver_src_Behat_Mink_Driver',
    'behat_mink_src_Behat_Mink',
    'channelgrabber_cache_CG_Cache',
//    'channelgrabber_codeception_CG_Codeception',
    'channelgrabber_constants_CG',
    'channelgrabber_etag_CG_ETag',
    'channelgrabber_http_CG_Http',
    'channelgrabber_order_CG_Order',
//    'channelgrabber_phinx_src_Phinx',
    'channelgrabber_predis_CG_Predis',
//    'channelgrabber_slim_CG_Slim',
    'channelgrabber_stdlib_CG_Stdlib',
    'channelgrabber_validation_CG_Validation',
    'channelgrabber_vnderror_CG_VndError',
//    'codeception_codeception_src_Codeception',
    'fabpot_goutte_Goutte',
    'guzzle_guzzle_src_Guzzle',
    'instaclick_php-webdriver_lib_WebDriver',
    'monolog_monolog_src_Monolog',
    'nocarrier_hal_src_Nocarrier',
    'phpspec_php-diff_lib_Diff',
    'phpspec_phpspec_src_PhpSpec',
    'phpspec_prophecy_src_Prophecy',
    'predis_predis_lib_Predis',
    'psr_log_Psr_Log',
    'slim_slim_Slim',
    'symfony_browser-kit_Symfony_Component_BrowserKit',
    'symfony_class-loader_Symfony_Component_ClassLoader',
    'symfony_config_Symfony_Component_Config',
    'symfony_console_Symfony_Component_Console',
    'symfony_css-selector_Symfony_Component_CssSelector',
    'symfony_dom-crawler_Symfony_Component_DomCrawler',
    'symfony_event-dispatcher_Symfony_Component_EventDispatcher',
    'symfony_filesystem_Symfony_Component_Filesystem',
    'symfony_finder_Symfony_Component_Finder',
    'symfony_process_Symfony_Component_Process',
    'symfony_yaml_Symfony_Component_Yaml',
//    'zendframework_zend-code_Zend_Code',
    'zendframework_zend-config_Zend_Config',
    'zendframework_zend-db_Zend_Db',
    'zendframework_zend-di_Zend_Di',
    'zendframework_zend-eventmanager_Zend_Eventmanager',
    'zendframework_zend-filter_Zend_Filter',
    'zendframework_zend-inputfilter_Zend_Inputfilter',
    'zendframework_zend-servicemanager_Zend_Servicemanager',
    'zendframework_zend-stdlib_Zend_Stdlib',
//    'zendframework_zend-validator_Zend_Validator',
);