# Load DSL and Setup Up Stages
require 'capistrano/setup'
import 'lib/sshkit/formatters/passthrough.rb'

# Includes default deployment tasks
require 'capistrano/deploy'

# Includes tasks from other gems included in your Gemfile

# Loads custom tasks from `tasks' if you have any defined.
Dir.glob('tasks/*.cap').each { |r| import r } if Dir.exists?('tasks')
