db.preference.insert({
    "_id":"1",
    "preference":{
        "orderTable":[
            "tags",
            "orderInformation",
            "shippingService",
            "dispatch"
        ],
        "other":1
    }
});
db.preference.insert({
    "_id":"2",
    "preference":{
        "orderTable":[
            "orderInformation",
            "shippingService",
            "dispatch",
            "tags"
        ],
        "other":2
    }
});
db.preference.insert({
    "_id":"3",
    "preference":{
        "orderTable":[
            "tags",
            "orderInformation",
            "shippingService",
            "dispatch",
            "invoice"
        ],
        "other":3
    }
});
db.preference.insert({
    "_id":"4",
    "preference":{
        "other":4
    }
});
db.preference.insert({
    "_id":"5",
    "preference":{
        "orderTable":[
            "checkbox",
            "orderInformation",
            "shippingService",
            "buyerName"
        ]
    }
});
